services:

  app:
    image: ghcr.io/l4rm4nd/memelord:latest # pin a minor version series tag instead of latest
    container_name: memelord
    environment:
      # see env.example for more setup options
      # ------------------------------------------------------------
      # your FQDN or IP; multiple ones supported by comma separation
      - DOMAIN=memelord.example.com
      # set to True if you use a reverse proxy with tls; enables secure cookie flag and hsts
      - SECURE_COOKIES=False
      # define the maximum session age in minutes
      - SESSION_COOKIE_AGE=30
      # decide whether session cookie is invalidated on browser close
      - SESSION_EXPIRE_AT_BROWSER_CLOSE=False
      # define the timezone
      - TZ=Europe/Berlin
    restart: unless-stopped
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./volume-data/database:/opt/app/database # persistent storage for sqlite3 database
      - ./volume-data/media:/opt/app/media # persistent storage for uploaded media    
    #networks:
    #  - proxy
    #  - internal
    #labels:
    #  - traefik.enable=true
    #  - traefik.docker.network=proxy
    #  - traefik.http.routers.memelord.rule=Host(`memelord.example.com`)
    #  - traefik.http.services.memelord.loadbalancer.server.port=8000
    #  # Optional part for traefik middlewares
    #  - traefik.http.routers.memelord.middlewares=local-ipwhitelist@file

#  db:
#    image: postgres:16-alpine
#    container_name: memelord-psql
#    restart: unless-stopped
#    expose:
#      - 5432
#    volumes:
#      - ./volume-data/database/psql:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=memelord
#      - POSTGRES_PASSWORD=memelord
#      - POSTGRES_DB=memelord
#    #networks:
#    #  - internal

#  redis:
#    image: redis:7-alpine
#    container_name: memelord-redis
#    restart: unless-stopped
#    expose:
#      - 6379
#    volumes:
#      - ./volume-data/redis:/data
#    # Enable Redis persistence with AOF (recommended for session storage)
#    command: redis-server --appendonly yes --appendfsync everysec
#    # Optional: Enable password authentication
#    #command: redis-server --appendonly yes --appendfsync everysec --requirepass your_password
#    #networks:
#    #  - internal

#networks:
#  proxy:
#    external: true
#  internal:
#    internal: true
