# Generated by Django 5.2.9 on 2026-01-19 10:13

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.meme_upload_to),
        ),
    ]
