# Generated by Django 5.2.9 on 2026-01-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_media_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='is_public',
        ),
        migrations.AddField(
            model_name='media',
            name='public_feed_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
